In [2]:
from numpy import *

In [4]:
a = array([[1,2,3,4], [5,6,7,8], [1,2,3,4]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [5]:
# 看a的类型
type(a)

numpy.ndarray

In [6]:
a[:, :-1]

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3]])

In [14]:
a = array([1,2,3,4,5,6,7,8])
print(a)
a.reshape(-1, 2)

[1 2 3 4 5 6 7 8]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
help(a.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.

